# docker-compose.yml

version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: almere-proxy
    restart: unless-stopped
    ports:
      # Expose standard HTTP port 80 to the host.
      # Your server will route traffic from your domain to this port.
      - "2075:80"
    volumes:
      # FIX: Mount the config file to the correct directory where server blocks are expected,
      # overwriting the default Nginx server configuration.
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - almere-net

  backend:
    build: ./backend
    container_name: almere-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    # Ports are no longer exposed to the host, only to the nginx proxy
    expose:
      - "3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - almere-net

  frontend:
    build: ./frontend
    container_name: almere-frontend
    restart: unless-stopped
    # Ports are no longer exposed to the host, only to the nginx proxy
    expose:
      - "5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - almere-net

networks:
  almere-net:
    driver: bridge