version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: almere-proxy-prod
    ports:
      - "${NGINX_HOST_PORT:-2075}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
     - almere-net
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: almere-backend-prod
    env_file: .env
    # VOLUMES are removed for production. The code is baked into the image.
    networks:
      - almere-net
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: almere-frontend-prod
    # ENVIRONMENT variables are no longer needed as they are baked into the static build.
    # VOLUMES are removed for production.
    networks:
      - almere-net
    expose:
      # The new frontend container runs Nginx on port 80
      - "80"
    restart: unless-stopped

networks:
  almere-net:
    driver: bridge



