# docker-compose.yml

version: '3.8'

services:
  backend:
    build: ./backend
    container_name: almere-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    # Volume mount for backend hot-reloading
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    # Use nodemon for hot-reloading in development
    command: npm run dev
    networks:
      - almere-net

  frontend:
    build: ./frontend
    container_name: almere-frontend
    restart: unless-stopped
    ports:
      # Vite's default port is 5173
      - "5173:5173"
    # Add environment variable to enable Vite's polling mechanism
    # This is crucial for hot-reloading to work reliably in Docker
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    # Volume mount for frontend hot-reloading
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - almere-net

networks:
  almere-net:
    driver: bridge