# Production-specific docker-compose file.
# To run: docker-compose up --build

services:
  nginx:
    image: nginx:alpine
    container_name: almere-proxy-prod
    ports:
      # The application will be accessible on http://localhost:2075
      - "${NGINX_HOST_PORT:-2075}:80"
    volumes:
      # Mount the production-specific nginx configuration
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
     - almere-net
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      # Use the standard production Dockerfile
      dockerfile: Dockerfile
    container_name: almere-backend-prod
    env_file: .env
    # MODIFIED: Added volumes to persist the SQLite database and all images.
    # The database is stored in the host's `./database` directory.
    # Source and generated images are stored in the host's `./backend/images` directory.
    volumes:
      - ./database:/app/database
      - ./backend/images:/app/images
    networks:
      - almere-net
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      # Use the standard production Dockerfile
      dockerfile: Dockerfile
    container_name: almere-frontend-prod
    # ENVIRONMENT variables are no longer needed as they are baked into the static build.
    # VOLUMES are removed for production.
    networks:
      - almere-net
    expose:
      # The frontend container runs Nginx on port 80
      - "80"
    restart: unless-stopped

networks:
  almere-net:
    driver: bridge




